### ISSUE TITLE
timer in Windows doesn't report microseconds?

### ISSUE THREAD

**Issue by erwincoumans** [mainroach/sandbox#2]
I realize this repo is dead, but its functionality seems still useful to profile C++ programs with Chrome about://tracing viewer.

This event_trace version logs the query_counter values ( which is the QueryPerformanceCounter value on Windows), which are not microseconds as required here (https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview)

The code ignores the query_counter_frequency.

inline void query_counter(timer_ticks *pTicks){
   QueryPerformanceCounter(reinterpret_cast<LARGE_INTEGER*>(pTicks));
}

Is there a more up-to-date version of this? 

Or should we extract it from Chromium (https://cs.chromium.org/chromium/src/base/trace_event/common/trace_event_common.h?q=f:trace_event_common.h&sq=package:chromium&type=cs&l=1) or write it from scratch?

**Comment by mainroach** [comment]
@erwincoumans [Catapult](https://catapult.gsrc.io/telemetry) is the proper place for all current and modern discussions of using the tracing library in Chrome. Please forward your query there.
